pagopa/idpay-timeline

src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java, src/test/java/it/gov/pagopa/timeline/dto/mapper/OperationMapperTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
=> ISB-225-sviluppo-update-della-timeline-sottosistema-beneficiario

.devops/deploy-pipelines.yml
=> ISB-544-aggiornamento-delle-configurazioni-su-nuovo-ambiente

src/main/java/it/gov/pagopa/timeline/service/TimelineServiceImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify performance log and info log
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: delete initiative fix performance log

postman/idpay-timeline-e2e.postman_collection.json
**Description**
The purpose of this PR is to update the functional tests to add the newly created delete initiative api call.
**List of changes**
-  Updated functional tests: added "Delete initiative" api call after an initiative creation.
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> feat: IDP 1614 adeguamento test timeline

.devops/deploy-pipelines.yml, .github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, .releaserc.json, Dockerfile, helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
This PR proposes several devops improvements:
- dependency version pinning
- helm chart upgrade
- new triggers on anchore action
- fix on release action
- new pull request template
- change anchore slack notification template
- add codeowners
=> fix: [IDP-1719] devops improvements on helm, actions and dockerfile

Dockerfile
=> fix: IDP-1760 fix new critical CVE-2022-48174 (#91)

pom.xml, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/utils/MemoryAppender.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/timeline/utils/AuditUtilitiesTest.java
=> feat: Release dev

src/main/java/it/gov/pagopa/timeline/dto/QueueCommandOperationDTO.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineRepository.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepository.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepositoryImpl.java, src/main/java/it/gov/pagopa/timeline/service/TimelineServiceImpl.java, src/test/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepositoryImplTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified QueueCommandOperationDTO
- Added paged delete method to extended repository
- Modified JUnit tests
=> fix: IDP-1848-Modified QueueCommandOperationDTO, added paged delete method to TimelineSpecificRepository, modified JUnit tests.

src/main/java/it/gov/pagopa/timeline/dto/DetailOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/QueueOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/mapper/OperationMapper.java, src/main/java/it/gov/pagopa/timeline/model/Operation.java, src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java, src/test/java/it/gov/pagopa/timeline/dto/mapper/OperationMapperTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
Update queue message for new idpayCode API 
=> feat: IDP-1802-implementazione-notifica

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/timeline/service/TimelineServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
The purpose of this pr is to change the method of getting parameters from the event dto to the application.yml
- Removed getting parameters from event dto
- Added pagination and delay parameters in application and values yaml
- Fixed Junit tests
=> fix: IDP 1848 idpay timeline delete

.devops/deploy-pipelines.yml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/timeline/dto/DetailOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/QueueCommandOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/QueueOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/mapper/OperationMapper.java, src/main/java/it/gov/pagopa/timeline/model/Operation.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineRepository.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepository.java, src/main/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepositoryImpl.java, src/main/java/it/gov/pagopa/timeline/service/TimelineServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java, src/test/java/it/gov/pagopa/timeline/dto/mapper/OperationMapperTest.java, src/test/java/it/gov/pagopa/timeline/repository/TimelineSpecificRepositoryImplTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
This PR includes:
- [IDP-1848](https://github.com/pagopa/idpay-timeline/pull/97)
- [IDP-1802](https://github.com/pagopa/idpay-timeline/pull/99)
[IDP-1848]: https://pagopa.atlassian.net/browse/IDP-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1802]: https://pagopa.atlassian.net/browse/IDP-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: promote to UAT

src/main/java/it/gov/pagopa/timeline/dto/OperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/mapper/OperationMapper.java
=> fix: Promote to uat

Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java
=> fix: Idp 2016 fix CVE

pom.xml, src/main/java/it/gov/pagopa/timeline/enums/ChannelTransaction.java, src/main/java/it/gov/pagopa/timeline/service/TimelineServiceImpl.java
- Added check for new chanels types 
=> feat: Check for new channels type

postman/idpay-timeline-e2e.postman_collection.json
=> chore: Idp 2027 adeguamento test api tramite postman

postman/idpay-timeline-e2e.postman_collection.json
- fix test api postman [PR](https://github.com/pagopa/idpay-timeline/commit/f9302e071959d227a75579f3e3d39bc9d08b051d)
=> fix: Promote UAT

src/main/java/it/gov/pagopa/common/config/HealthIndicatorLogger.java, src/test/java/it/gov/pagopa/common/config/HealthIndicatorLoggerTest.java
Add HealthIndicatorLogger
IDP 1125
=> fix: [IDP-1125] Log actuator health

src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionPayload.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionResponse.java, src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java, src/main/java/it/gov/pagopa/timeline/configuration/TimelineErrorManagerConfig.java, src/main/java/it/gov/pagopa/timeline/constants/TimelineConstants.java, src/main/java/it/gov/pagopa/timeline/exception/ControllerExceptionHandler.java, src/main/java/it/gov/pagopa/timeline/exception/custom/RefundsNotFoundException.java, src/main/java/it/gov/pagopa/timeline/exception/custom/TimelineDetailNotFoundException.java, src/main/java/it/gov/pagopa/timeline/exception/custom/UserNotFoundException.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java, src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
The purpose of this PR is to fix exception handling in common package
- Added new interface ServiceExceptionResponse
- Update handle of ServiceExceptionHandler
- Update jUnit
=> fix: handle common package exceptions

Dockerfile, pom.xml, src/main/java/it/gov/pagopa/timeline/controller/TimelineController.java, src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java
fix: IDP-2196 fix Cve
fix: IDP-1565 handling negative page number
=> fix: Release dev

helm/values.yaml, src/main/resources/application.yml
- Update timeline topic configuration into helm and application.yml
=> chore: [IDP-2270] move references timeline topic from eventHub00 to eventHub01

postman/idpay-timeline-e2e.postman_collection.json
Task [IDP-2129](https://pagopa.atlassian.net/browse/IDP-2129)
- removed real cf from test
[IDP-2129]: https://pagopa.atlassian.net/browse/IDP-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [IDP-2129] remove real cf from postman

postman/idpay-timeline-e2e.postman_collection.json, src/main/java/it/gov/pagopa/timeline/dto/DetailOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/OperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/QueueOperationDTO.java, src/main/java/it/gov/pagopa/timeline/dto/mapper/OperationMapper.java, src/main/java/it/gov/pagopa/timeline/model/Operation.java, src/test/java/it/gov/pagopa/timeline/controller/TimelineControllerTest.java, src/test/java/it/gov/pagopa/timeline/dto/mapper/OperationMapperTest.java, src/test/java/it/gov/pagopa/timeline/service/TimelineServiceTest.java
- Handle decimal value and update postman
=> fix: [IDP-2503] handle decimal value and update postman

specs/asyncapi.yml
=> chore: [Idp 2494] added async documentation

Dockerfile, specs/asyncapi.yml
=> chore: promotion to main - change image to fix cve

Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml, src/main/resources/application.yml
- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
=> chore: Update dependencies

Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml
- Fix CVE [PR](https://github.com/pagopa/idpay-timeline/pull/148)
=> chore: promote to MAIN

Dockerfile, pom.xml
=> fix: fix cve
